// src/routes/Header.svelte
<script>
	import { page } from '$app/stores';
	import logo from '$lib/images/svelte-logo.svg';
	import github from '$lib/images/github.svg';
	import horseLogo from '$lib/images/horse.png';

	const loggedIn = false;
	const selectedCompetition = {
		name: 'Dave Test Comp'
	};
</script>


<header>
	{#if loggedIn}
		<TopMenu
			path={path}
			user={user}
			competitions={competitions}
			selectedCompetition={selectedCompetition}
			handleCompetitionSelect={handleCompetitionSelect}
			isAdmin={isAdmin}
		/>
		<img class="profile-pic" src={'pics/' + user.image} alt="profile-pic" title={`${user.name.first} ${user.name.last}`} />
		<button class="reload-btn" title="Reload data" on:click={onReloadData}>
			<span class="icon-reload" />
		</button>
	{/if}

	<h2>
		Spring Racing Tipping <img src={horseLogo} alt="Title logo" />
		<span class="beta">BETA</span>
	</h2>

	{#if loggedIn}
		<span class="comp-name">{selectedCompetition.name}</span>
	{/if}



	<div class="corner">
		<a href="https://kit.svelte.dev">
			<img src={logo} alt="SvelteKit" />
		</a>
	</div>

	<nav>
		<svg viewBox="0 0 2 3" aria-hidden="true">
			<path d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z" />
		</svg>
		<ul>
			<li aria-current={$page.url.pathname === '/' ? 'page' : undefined}>
				<a href="/">Home</a>
			</li>
			<li aria-current={$page.url.pathname === '/about' ? 'page' : undefined}>
				<a href="/about">About</a>
			</li>
			<li aria-current={$page.url.pathname.startsWith('/sverdle') ? 'page' : undefined}>
				<a href="/sverdle">Sverdle</a>
			</li>
		</ul>
		<svg viewBox="0 0 2 3" aria-hidden="true">
			<path d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z" />
		</svg>
	</nav>

	<div class="corner">
		<a href="https://github.com/sveltejs/kit">
			<img src={github} alt="GitHub" />
		</a>
	</div>
</header>

<style>
	
</style>

// src/components/Header.jsx
import React, { Component } from 'react';
import TopMenu from './TopMenu';

export default class Header extends Component {
    constructor(props) {
        super(props);
        this.state = {
            showLogOut: false
        };
    }

    /* Determines whether React should re-render the component, in this case if the new props are different from the old props,
       or if the new state is different from the current state. */
    shouldComponentUpdate(nextProps, nextState) {
        return !(nextProps === this.props && nextState === this.state);
    }

    /* Updates the state to show the log out overlay when the user has clicked the profile picture. */
    handleShowLogOutOverlay = () => {
        this.setState({
            showLogOut: true
        });
    };

    /* Updates the state to hide the log out overlay when the user has clicked on the overlay background. */
    handleHideLogOutOverlay = () => {
        this.setState({
            showLogOut: false
        });
    };

    /* Function to render the component. */
    render() {
        return (
            <>
                {
                    // Show the top menu on every page but the Login page.
                    this.props.page !== 'Log In' &&
                    <TopMenu
                        path={this.props.path}
                        user={this.props.user}
                        competitions={this.props.competitions}
                        selectedCompetition={this.props.selectedCompetition}
                        handleCompetitionSelect={this.props.handleCompetitionSelect}
                        isAdmin={this.props.isAdmin}
                    />
                }
                {
                    // Show the reload button on every page but the Login page.
                    this.props.page !== 'Log In' &&
                    <button className="reload-btn" onClick={this.props.onReloadData}>
                        <span className="icon-reload" />
                    </button>
                }
                <h2>
                    Spring Racing Tipping <img src="horse.png" alt="Title logo" />
                    <span className="beta">BETA</span>
                </h2>
                {
                    // Show the competition name on every page but the Login page, and if the selectedCompetition is set.
                    this.props.page !== 'Log In' && this.props.selectedCompetition &&
                    <span className="comp-name">{this.props.selectedCompetition.name}</span>
                }
                <h3>{this.props.page}</h3>
                <p>{this.props.text}</p>
            </>
        );
    }
}
